# Generated by Django 5.0.6 on 2025-05-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_producto_categoria_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={},
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='fecha_creacion',
            new_name='creado',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='fecha_actualizacion',
        ),
        migrations.AddField(
            model_name='comentario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='comentarios/'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='titulo',
            field=models.CharField(default='Sin título', max_length=100),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=models.TextField(),
        ),
    ]
